# Generated by Django 3.0.3 on 2020-03-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('main_title', models.CharField(max_length=50, verbose_name='main_title')),
                ('sub_title', models.CharField(max_length=50, verbose_name='sub_title')),
                ('content', models.TextField()),
                ('article_type', models.IntegerField(choices=[(0, 'Python'), (1, 'JavaScript'), (2, 'SQL')], default=0)),
            ],
        ),
    ]
