# Generated by Django 3.0.3 on 2020-03-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(editable=False, max_length=50, verbose_name='article_title')),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='upload')),
                ('article_type', models.IntegerField(choices=[(0, 'Python'), (1, 'Other')], default=0)),
            ],
        ),
    ]
